# Use an ARM-based Ubuntu image
FROM ubuntu:latest

# Install necessary packages
# RUN apt-get update && apt-get install -y wget ca-certificates dpkg

# Keep the container running indefinitely to allow exec into it
CMD ["sleep", "infinity"]
